# Generated by Django 2.1.7 on 2019-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20190314_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_src',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
