# Generated by Django 2.1.7 on 2019-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20190318_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='desire_price',
            field=models.IntegerField(max_length=30),
        ),
    ]
