# Generated by Django 2.1.7 on 2019-03-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20190315_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='myurl',
            new_name='product_url',
        ),
    ]
