# Generated by Django 2.1.7 on 2019-03-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20190323_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='desire_price',
            field=models.FloatField(max_length=30),
        ),
    ]
